import type { WorkflowTemplate } from '@cloudscode/shared';

export const BUILTIN_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'add-api-endpoint',
    projectId: null,
    name: 'Add API Endpoint',
    description: 'Create a new API endpoint with proper patterns, validation, and tests.',
    category: 'development',
    isBuiltin: true,
    createdAt: 0,
    updatedAt: 0,
    steps: [
      {
        id: 'analyze-patterns',
        title: 'Analyze existing API patterns',
        description: 'Review the existing API endpoints, routing patterns, middleware usage, request/response conventions, and error handling to ensure the new endpoint follows established patterns.',
        agentType: 'code-analyst',
        estimatedComplexity: 'low',
        dependencies: [],
      },
      {
        id: 'implement-endpoint',
        title: 'Implement the endpoint',
        description: 'Create the new API endpoint following the patterns identified in the analysis step. Include route definition, handler logic, request validation, and proper error handling.',
        agentType: 'implementer',
        estimatedComplexity: 'medium',
        dependencies: ['analyze-patterns'],
      },
      {
        id: 'test-endpoint',
        title: 'Write and run tests',
        description: 'Create tests for the new endpoint covering success cases, error cases, and edge cases. Run the tests to verify everything works.',
        agentType: 'test-runner',
        estimatedComplexity: 'medium',
        dependencies: ['implement-endpoint'],
        qualityGate: {
          type: 'test-pass',
          description: 'All endpoint tests must pass',
          required: true,
        },
      },
      {
        id: 'document-endpoint',
        title: 'Document the endpoint',
        description: 'Add inline documentation and update any API docs with the new endpoint details, including request/response schemas and usage examples.',
        agentType: 'implementer',
        estimatedComplexity: 'low',
        dependencies: ['test-endpoint'],
      },
    ],
  },
  {
    id: 'fix-bug',
    projectId: null,
    name: 'Fix Bug',
    description: 'Systematically reproduce, diagnose, fix, and verify a bug.',
    category: 'maintenance',
    isBuiltin: true,
    createdAt: 0,
    updatedAt: 0,
    steps: [
      {
        id: 'reproduce-bug',
        title: 'Reproduce the bug',
        description: 'Analyze the bug report, identify the reproduction steps, and locate the relevant code paths. Confirm the issue exists and document expected vs actual behavior.',
        agentType: 'code-analyst',
        estimatedComplexity: 'medium',
        dependencies: [],
      },
      {
        id: 'analyze-root-cause',
        title: 'Analyze root cause',
        description: 'Trace through the code to identify the root cause of the bug. Examine related code, dependencies, and recent changes that may have introduced the issue.',
        agentType: 'code-analyst',
        estimatedComplexity: 'medium',
        dependencies: ['reproduce-bug'],
      },
      {
        id: 'implement-fix',
        title: 'Implement the fix',
        description: 'Apply the fix for the identified root cause. Make minimal, targeted changes that address the bug without introducing side effects.',
        agentType: 'implementer',
        estimatedComplexity: 'medium',
        dependencies: ['analyze-root-cause'],
      },
      {
        id: 'verify-fix',
        title: 'Verify the fix',
        description: 'Run existing tests and add new tests if needed to verify the bug is fixed and no regressions were introduced.',
        agentType: 'test-runner',
        estimatedComplexity: 'medium',
        dependencies: ['implement-fix'],
        qualityGate: {
          type: 'test-pass',
          description: 'All tests must pass after the fix',
          required: true,
        },
      },
    ],
  },
  {
    id: 'add-feature',
    projectId: null,
    name: 'Add Feature',
    description: 'Design, implement, test, and integrate a new feature.',
    category: 'development',
    isBuiltin: true,
    createdAt: 0,
    updatedAt: 0,
    steps: [
      {
        id: 'design-feature',
        title: 'Design the feature',
        description: 'Research existing codebase patterns, identify where the feature fits, design the implementation approach, and plan the integration points.',
        agentType: 'researcher',
        estimatedComplexity: 'medium',
        dependencies: [],
      },
      {
        id: 'implement-feature',
        title: 'Implement the feature',
        description: 'Build the feature according to the design, following existing code patterns and conventions. Create all necessary files, components, and integrations.',
        agentType: 'implementer',
        estimatedComplexity: 'high',
        dependencies: ['design-feature'],
      },
      {
        id: 'test-feature',
        title: 'Write and run tests',
        description: 'Create comprehensive tests for the new feature covering unit tests, integration tests, and edge cases. Run all tests to verify functionality.',
        agentType: 'test-runner',
        estimatedComplexity: 'medium',
        dependencies: ['implement-feature'],
        qualityGate: {
          type: 'test-pass',
          description: 'All feature tests must pass',
          required: true,
        },
      },
      {
        id: 'integration-verify',
        title: 'Verify integration',
        description: 'Verify the feature integrates correctly with the existing system. Check for conflicts, ensure backward compatibility, and validate the complete workflow.',
        agentType: 'code-analyst',
        estimatedComplexity: 'low',
        dependencies: ['test-feature'],
      },
    ],
  },
  {
    id: 'refactor-component',
    projectId: null,
    name: 'Refactor Component',
    description: 'Safely refactor a component with dependency analysis, implementation, and verification.',
    category: 'maintenance',
    isBuiltin: true,
    createdAt: 0,
    updatedAt: 0,
    steps: [
      {
        id: 'analyze-deps',
        title: 'Analyze dependencies',
        description: 'Map all dependencies, usages, and consumers of the component to be refactored. Identify potential impact areas and create a refactoring plan.',
        agentType: 'code-analyst',
        estimatedComplexity: 'medium',
        dependencies: [],
      },
      {
        id: 'refactor',
        title: 'Perform refactoring',
        description: 'Execute the refactoring according to the analysis. Update the component and all affected consumers. Maintain backward compatibility where needed.',
        agentType: 'implementer',
        estimatedComplexity: 'high',
        dependencies: ['analyze-deps'],
      },
      {
        id: 'test-refactor',
        title: 'Run tests',
        description: 'Run all existing tests to verify the refactoring did not introduce regressions. Add new tests if the refactored code has new patterns that need coverage.',
        agentType: 'test-runner',
        estimatedComplexity: 'medium',
        dependencies: ['refactor'],
        qualityGate: {
          type: 'test-pass',
          description: 'All tests must pass after refactoring',
          required: true,
        },
      },
      {
        id: 'verify-refactor',
        title: 'Verify refactoring',
        description: 'Review the refactored code for quality, verify all consumers work correctly, and confirm no dead code or unused imports remain.',
        agentType: 'code-analyst',
        estimatedComplexity: 'low',
        dependencies: ['test-refactor'],
      },
    ],
  },
];
